#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# Ultimate Self-Hosted Stack Installer
# ============================================================

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Storage box defaults — overridden by prompt_storage_box if the user opts in
USE_STORAGE_BOX=false
STORAGEBOX_HOST=""
STORAGEBOX_USER=""
STORAGEBOX_MOUNT="/mnt/storagebox"
DOWNLOADS_DIR="./data/downloads"
MEDIA_DIR_LOCAL="./data/media"
DOWNLOADS_DIR_LOCAL="./data/downloads"

print_banner() {
  echo -e "${BLUE}${BOLD}"
  cat << 'BANNER'
╔══════════════════════════════════════════════════════════════╗
║           Ultimate Self-Hosted Stack Installer               ║
║                                                              ║
║  Traefik · Authentik · Homarr · Jellyfin · Nextcloud        ║
║  Navidrome · Sonarr/Radarr/Lidarr · Headscale · VPN        ║
║  Vaultwarden · Grafana · Uptime Kuma · and more...          ║
╚══════════════════════════════════════════════════════════════╝
BANNER
  echo -e "${NC}"
}

info()    { echo -e "${CYAN}[INFO]${NC}  $*"; }
success() { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; }
step()    { echo -e "\n${BOLD}${BLUE}▶ $*${NC}"; }

die() { error "$*"; exit 1; }

check_requirements() {
  step "Checking requirements"
  local missing=()

  command -v docker   &>/dev/null || missing+=("docker")
  docker compose version &>/dev/null 2>&1 || missing+=("docker-compose-plugin (v2)")
  command -v curl     &>/dev/null || missing+=("curl")
  command -v openssl  &>/dev/null || missing+=("openssl")
  command -v python3  &>/dev/null || true  # python3 optional (used for Authentik API rename)

  if [[ ${#missing[@]} -gt 0 ]]; then
    die "Missing required tools: ${missing[*]}"
  fi

  # Verify Docker daemon is running
  docker info &>/dev/null || die "Docker daemon is not running"

  success "All requirements met"
}

gen_secret()   { openssl rand -hex 32; }
gen_short_id() { openssl rand -hex 8; }

prompt_config() {
  step "Configuration"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

  while [[ -z "${ADMIN_USER:-}" ]]; do
    read -rp "$(echo -e "${YELLOW}Admin username${NC}: ")" ADMIN_USER
  done

  while true; do
    read -rsp "$(echo -e "${YELLOW}Admin password${NC}: ")" ADMIN_PASSWORD; echo
    read -rsp "$(echo -e "${YELLOW}Confirm password${NC}: ")" _confirm; echo
    [[ "$ADMIN_PASSWORD" == "$_confirm" ]] && [[ -n "$ADMIN_PASSWORD" ]] && break
    warn "Passwords do not match or are empty — try again"
  done

  while [[ -z "${DOMAIN:-}" ]]; do
    read -rp "$(echo -e "${YELLOW}Fully qualified domain (e.g. example.com)${NC}: ")" DOMAIN
    # Strip protocol/trailing slash
    DOMAIN="${DOMAIN#https://}"; DOMAIN="${DOMAIN#http://}"; DOMAIN="${DOMAIN%/}"
  done

  read -rp "$(echo -e "${YELLOW}Admin email${NC} [admin@${DOMAIN}]: ")" ADMIN_EMAIL
  ADMIN_EMAIL="${ADMIN_EMAIL:-admin@${DOMAIN}}"

  read -rp "$(echo -e "${YELLOW}Timezone${NC} [America/New_York]: ")" TZ
  TZ="${TZ:-America/New_York}"

  read -rp "$(echo -e "${YELLOW}Media directory${NC} [./data/media]: ")" MEDIA_DIR
  MEDIA_DIR="${MEDIA_DIR:-./data/media}"

  read -rp "$(echo -e "${YELLOW}PUID${NC} [1000]: ")" PUID
  PUID="${PUID:-1000}"

  read -rp "$(echo -e "${YELLOW}PGID${NC} [1000]: ")" PGID
  PGID="${PGID:-1000}"

  echo ""
  success "Configuration captured"
}

generate_secrets() {
  step "Generating secrets"

  POSTGRES_PASSWORD=$(gen_secret)
  REDIS_PASSWORD=$(gen_secret)
  AUTHENTIK_SECRET_KEY=$(gen_secret)
  AUTHENTIK_BOOTSTRAP_TOKEN=$(gen_secret)
  NEXTCLOUD_DB_PASSWORD=$(gen_secret)
  BOOKLORE_DB_PASSWORD=$(gen_secret)
  BOOKLORE_DB_ROOT_PASSWORD=$(gen_secret)

  HOMARR_OIDC_CLIENT_ID="homarr-$(gen_short_id)"
  HOMARR_OIDC_CLIENT_SECRET=$(gen_secret)

  AUDIOBOOKSHELF_OIDC_CLIENT_ID="abs-$(gen_short_id)"
  AUDIOBOOKSHELF_OIDC_CLIENT_SECRET=$(gen_secret)

  NEXTCLOUD_OIDC_CLIENT_ID="nextcloud-$(gen_short_id)"
  NEXTCLOUD_OIDC_CLIENT_SECRET=$(gen_secret)

  GRAFANA_OIDC_CLIENT_ID="grafana-$(gen_short_id)"
  GRAFANA_OIDC_CLIENT_SECRET=$(gen_secret)

  VAULTWARDEN_OIDC_CLIENT_ID="vaultwarden-$(gen_short_id)"
  VAULTWARDEN_OIDC_CLIENT_SECRET=$(gen_secret)

  HOMARR_SECRET_KEY=$(gen_secret)

  success "Secrets generated"
}

write_env() {
  step "Writing .env"

  cat > .env << EOF
# ================================================================
# Generated by install.sh — DO NOT COMMIT THIS FILE
# ================================================================

# ── Core ─────────────────────────────────────────────────────────
DOMAIN=${DOMAIN}
ADMIN_USER=${ADMIN_USER}
ADMIN_PASSWORD=${ADMIN_PASSWORD}
ADMIN_EMAIL=${ADMIN_EMAIL}
TZ=${TZ}
PUID=${PUID}
PGID=${PGID}
MEDIA_DIR=${MEDIA_DIR}
DOWNLOADS_DIR=${DOWNLOADS_DIR}
MEDIA_DIR_LOCAL=${MEDIA_DIR_LOCAL}
DOWNLOADS_DIR_LOCAL=${DOWNLOADS_DIR_LOCAL}

# ── Storage Box ───────────────────────────────────────────────────
USE_STORAGE_BOX=${USE_STORAGE_BOX}
STORAGEBOX_HOST=${STORAGEBOX_HOST}
STORAGEBOX_USER=${STORAGEBOX_USER}
STORAGEBOX_SHARE=${STORAGEBOX_SHARE:-backup}
STORAGEBOX_MOUNT=${STORAGEBOX_MOUNT}

# ── Databases ────────────────────────────────────────────────────
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
REDIS_PASSWORD=${REDIS_PASSWORD}
NEXTCLOUD_DB_PASSWORD=${NEXTCLOUD_DB_PASSWORD}
BOOKLORE_DB_PASSWORD=${BOOKLORE_DB_PASSWORD}
BOOKLORE_DB_ROOT_PASSWORD=${BOOKLORE_DB_ROOT_PASSWORD}

# ── Authentik ────────────────────────────────────────────────────
AUTHENTIK_SECRET_KEY=${AUTHENTIK_SECRET_KEY}
AUTHENTIK_BOOTSTRAP_TOKEN=${AUTHENTIK_BOOTSTRAP_TOKEN}

# ── OIDC Clients ─────────────────────────────────────────────────
HOMARR_OIDC_CLIENT_ID=${HOMARR_OIDC_CLIENT_ID}
HOMARR_OIDC_CLIENT_SECRET=${HOMARR_OIDC_CLIENT_SECRET}
HOMARR_SECRET_KEY=${HOMARR_SECRET_KEY}

AUDIOBOOKSHELF_OIDC_CLIENT_ID=${AUDIOBOOKSHELF_OIDC_CLIENT_ID}
AUDIOBOOKSHELF_OIDC_CLIENT_SECRET=${AUDIOBOOKSHELF_OIDC_CLIENT_SECRET}

NEXTCLOUD_OIDC_CLIENT_ID=${NEXTCLOUD_OIDC_CLIENT_ID}
NEXTCLOUD_OIDC_CLIENT_SECRET=${NEXTCLOUD_OIDC_CLIENT_SECRET}

GRAFANA_OIDC_CLIENT_ID=${GRAFANA_OIDC_CLIENT_ID}
GRAFANA_OIDC_CLIENT_SECRET=${GRAFANA_OIDC_CLIENT_SECRET}

VAULTWARDEN_OIDC_CLIENT_ID=${VAULTWARDEN_OIDC_CLIENT_ID}
VAULTWARDEN_OIDC_CLIENT_SECRET=${VAULTWARDEN_OIDC_CLIENT_SECRET}

EOF

  chmod 600 .env
  success ".env written (permissions 600)"
}

create_directories() {
  step "Creating directory structure"

  local dirs=(
    data/traefik
    data/authentik/media
    data/authentik/custom-templates
    data/homarr/appdata
    data/jellyfin/config
    data/jellyfin/cache
    data/jellyseerr
    data/audiobookshelf/config
    data/audiobookshelf/metadata
    data/booklore
    data/booklore-db
    data/booklore-bookdrop
    data/navidrome
    data/sonarr
    data/radarr
    data/lidarr
    data/prowlarr
    data/qbittorrent
    data/nextcloud
    data/headscale
    data/wireguard
    data/uptime-kuma
    data/prometheus
    data/grafana
    data/vaultwarden
    data/media/movies
    data/media/tv
    data/media/music
    data/media/books
    data/media/audiobooks
    data/media/podcasts
    data/downloads/complete
    data/downloads/incomplete
  )

  for d in "${dirs[@]}"; do
    mkdir -p "$d"
  done

  # acme.json must be 600 or Traefik refuses to use it
  touch data/traefik/acme.json
  chmod 600 data/traefik/acme.json

  # Grafana runs as UID/GID 472 — fix ownership so it can write its data dir
  chown -R 472:472 data/grafana 2>/dev/null || true

  # Pre-seed ARR service configs so they start with External auth.
  # Without this they default to Forms auth and show a second login screen
  # even though Authentik forward-auth is already protecting the route.
  # Only written on fresh install — never overwrites an existing config.
  local arr_xml
  arr_xml='<?xml version="1.0" encoding="utf-8"?>
<Config>
  <AuthenticationMethod>External</AuthenticationMethod>
  <AuthenticationRequired>Enabled</AuthenticationRequired>
  <LogLevel>info</LogLevel>
  <AnalyticsEnabled>False</AnalyticsEnabled>
</Config>'

  for svc in sonarr radarr lidarr prowlarr; do
    local cfg="data/${svc}/config.xml"
    if [[ ! -f "$cfg" ]]; then
      echo "$arr_xml" > "$cfg"
      chown "${PUID}:${PGID}" "$cfg" 2>/dev/null || true
      info "  Pre-configured ${svc}: auth=External"
    fi
  done

  success "Directories created"
}

process_templates() {
  step "Processing configuration templates"

  find config -name "*.template" | while read -r tmpl; do
    local output="${tmpl%.template}"
    sed \
      -e "s|{{DOMAIN}}|${DOMAIN}|g" \
      -e "s|{{ADMIN_USER}}|${ADMIN_USER}|g" \
      -e "s|{{ADMIN_EMAIL}}|${ADMIN_EMAIL}|g" \
      -e "s|{{POSTGRES_PASSWORD}}|${POSTGRES_PASSWORD}|g" \
      -e "s|{{REDIS_PASSWORD}}|${REDIS_PASSWORD}|g" \
      -e "s|{{AUTHENTIK_SECRET_KEY}}|${AUTHENTIK_SECRET_KEY}|g" \
      -e "s|{{AUTHENTIK_BOOTSTRAP_TOKEN}}|${AUTHENTIK_BOOTSTRAP_TOKEN}|g" \
      -e "s|{{HOMARR_OIDC_CLIENT_ID}}|${HOMARR_OIDC_CLIENT_ID}|g" \
      -e "s|{{HOMARR_OIDC_CLIENT_SECRET}}|${HOMARR_OIDC_CLIENT_SECRET}|g" \
      -e "s|{{AUDIOBOOKSHELF_OIDC_CLIENT_ID}}|${AUDIOBOOKSHELF_OIDC_CLIENT_ID}|g" \
      -e "s|{{AUDIOBOOKSHELF_OIDC_CLIENT_SECRET}}|${AUDIOBOOKSHELF_OIDC_CLIENT_SECRET}|g" \
      -e "s|{{NEXTCLOUD_OIDC_CLIENT_ID}}|${NEXTCLOUD_OIDC_CLIENT_ID}|g" \
      -e "s|{{NEXTCLOUD_OIDC_CLIENT_SECRET}}|${NEXTCLOUD_OIDC_CLIENT_SECRET}|g" \
      -e "s|{{GRAFANA_OIDC_CLIENT_ID}}|${GRAFANA_OIDC_CLIENT_ID}|g" \
      -e "s|{{GRAFANA_OIDC_CLIENT_SECRET}}|${GRAFANA_OIDC_CLIENT_SECRET}|g" \
      -e "s|{{VAULTWARDEN_OIDC_CLIENT_ID}}|${VAULTWARDEN_OIDC_CLIENT_ID}|g" \
      -e "s|{{VAULTWARDEN_OIDC_CLIENT_SECRET}}|${VAULTWARDEN_OIDC_CLIENT_SECRET}|g" \
      -e "s|{{NEXTCLOUD_DB_PASSWORD}}|${NEXTCLOUD_DB_PASSWORD}|g" \
      -e "s|{{TZ}}|${TZ}|g" \
      "$tmpl" > "$output"
    info "  $(basename "$tmpl") → $(basename "$output")"
  done

  success "Templates processed"
}

start_stack() {
  step "Starting the stack"

  info "[1/5] Pulling images (this may take several minutes)..."
  docker compose pull --quiet

  info "[2/5] Starting databases..."
  docker compose up -d postgres redis

  info "      Waiting for PostgreSQL..."
  local retries=0
  until docker compose exec -T postgres pg_isready -U postgres &>/dev/null; do
    retries=$((retries+1))
    [[ $retries -gt 30 ]] && die "PostgreSQL did not become healthy in time"
    sleep 2
  done
  success "      PostgreSQL ready"

  info "      Waiting for Redis..."
  retries=0
  until docker compose exec -T redis redis-cli -a "${REDIS_PASSWORD}" ping &>/dev/null; do
    retries=$((retries+1))
    [[ $retries -gt 20 ]] && die "Redis did not become healthy in time"
    sleep 2
  done
  success "      Redis ready"

  info "[3/5] Starting Authentik (first run takes ~90s)..."
  docker compose up -d authentik-server authentik-worker

  info "      Waiting for Authentik API (first run runs DB migrations — allow ~90s)..."
  retries=0
  until docker compose exec -T authentik-server /lifecycle/ak healthcheck &>/dev/null 2>&1; do
    retries=$((retries+1))
    [[ $retries -gt 60 ]] && die "Authentik did not become healthy after ~3 minutes. Check: docker compose logs authentik-server"
    sleep 3
  done
  success "      Authentik ready"

  if [[ "${ADMIN_USER}" != "akadmin" ]]; then
    info "      Renaming Authentik default user 'akadmin' → '${ADMIN_USER}'..."
    # Bootstrap writes akadmin AFTER the healthcheck passes — retry until the token is valid
    local user_pk="" rename_retries=0
    until [[ -n "$user_pk" ]] || [[ $rename_retries -gt 15 ]]; do
      user_pk=$(docker compose exec -T authentik-server \
        curl -sf \
          -H "Authorization: Bearer ${AUTHENTIK_BOOTSTRAP_TOKEN}" \
          "http://localhost:9000/api/v3/core/users/?username=akadmin" \
        | python3 -c "import sys,json; d=json.load(sys.stdin); print(d['results'][0]['pk'])" 2>/dev/null || true)
      [[ -z "$user_pk" ]] && { rename_retries=$((rename_retries+1)); sleep 3; }
    done

    if [[ -n "$user_pk" ]]; then
      docker compose exec -T authentik-server \
        curl -sf -X PATCH \
          -H "Authorization: Bearer ${AUTHENTIK_BOOTSTRAP_TOKEN}" \
          -H "Content-Type: application/json" \
          -d "{\"username\": \"${ADMIN_USER}\", \"name\": \"${ADMIN_USER}\"}" \
          "http://localhost:9000/api/v3/core/users/${user_pk}/" > /dev/null \
        && success "      Authentik admin username set to '${ADMIN_USER}'" \
        || warn "Could not rename akadmin — log in to Authentik as 'akadmin' and rename manually"
    else
      warn "Could not find akadmin user after 45s — log in to Authentik as 'akadmin' and rename manually"
    fi
  fi

  info "[4/5] Starting remaining services..."
  docker compose up -d

  info "[5/5] Waiting for all services to stabilize..."
  sleep 10

  success "Stack started"
}

configure_services() {
  step "Configuring services"

  local all_ok=true

  run_config_script() {
    local label="$1" script="$2"
    info "${label}..."
    if bash "${script}"; then
      success "      ${label} — done"
    else
      warn "      ${label} failed — re-run: ${script}"
      all_ok=false
    fi
  }

  run_config_script "Nextcloud OIDC"          scripts/configure-nextcloud-oidc.sh
  run_config_script "Audiobookshelf OIDC"     scripts/configure-audiobookshelf-oidc.sh
  run_config_script "Uptime Kuma admin"       scripts/configure-uptime-kuma.sh
  run_config_script "qBittorrent credentials" scripts/configure-qbittorrent.sh

  info "Headscale user + pre-auth key..."
  bash scripts/configure-headscale.sh || {
    warn "      Headscale setup failed — re-run: scripts/configure-headscale.sh"
    all_ok=false
  }

  [[ "$all_ok" == "true" ]] \
    && success "All services configured" \
    || warn "Some configuration steps failed — see warnings above"
}

print_summary() {
  echo ""
  echo -e "${GREEN}${BOLD}"
  cat << 'DONE'
╔══════════════════════════════════════════════════════════════╗
║                    Setup Complete!  🎉                       ║
╚══════════════════════════════════════════════════════════════╝
DONE
  echo -e "${NC}"

  echo -e "${BOLD}Service URLs:${NC}"
  printf "  %-18s → ${BLUE}https://home.%s${NC}\n"       "Dashboard (Homarr)"    "${DOMAIN}"
  printf "  %-18s → ${BLUE}https://auth.%s${NC}\n"       "Auth (Authentik)"      "${DOMAIN}"
  printf "  %-18s → ${BLUE}https://jellyfin.%s${NC}\n"   "Jellyfin"              "${DOMAIN}"
  printf "  %-18s → ${BLUE}https://requests.%s${NC}\n"   "Jellyseerr"            "${DOMAIN}"
  printf "  %-18s → ${BLUE}https://audiobooks.%s${NC}\n" "Audiobookshelf"        "${DOMAIN}"
  printf "  %-18s → ${BLUE}https://music.%s${NC}\n"      "Navidrome"             "${DOMAIN}"
  printf "  %-18s → ${BLUE}https://sonarr.%s${NC}\n"     "Sonarr"                "${DOMAIN}"
  printf "  %-18s → ${BLUE}https://radarr.%s${NC}\n"     "Radarr"                "${DOMAIN}"
  printf "  %-18s → ${BLUE}https://lidarr.%s${NC}\n"     "Lidarr"                "${DOMAIN}"
  printf "  %-18s → ${BLUE}https://prowlarr.%s${NC}\n"   "Prowlarr"              "${DOMAIN}"
  printf "  %-18s → ${BLUE}https://qbit.%s${NC}\n"       "qBittorrent"           "${DOMAIN}"
  printf "  %-18s → ${BLUE}https://cloud.%s${NC}\n"      "Nextcloud"             "${DOMAIN}"
  printf "  %-18s → ${BLUE}https://headscale.%s${NC}\n"  "Headscale"             "${DOMAIN}"
  printf "  %-18s → ${BLUE}https://vpn.%s${NC}\n"        "WireGuard Easy"        "${DOMAIN}"
  printf "  %-18s → ${BLUE}https://uptime.%s${NC}\n"     "Uptime Kuma"           "${DOMAIN}"
  printf "  %-18s → ${BLUE}https://grafana.%s${NC}\n"    "Grafana"               "${DOMAIN}"
  printf "  %-18s → ${BLUE}https://vault.%s${NC}\n"      "Vaultwarden"           "${DOMAIN}"
  printf "  %-18s → ${BLUE}https://traefik.%s${NC}\n"    "Traefik Dashboard"     "${DOMAIN}"

  echo ""
  echo -e "${BOLD}Admin credentials:${NC}"
  echo -e "  Username: ${GREEN}${ADMIN_USER}${NC}"
  echo -e "  Password: ${GREEN}(the password you entered)${NC}"
  echo ""
  echo -e "${BOLD}Headscale client connection:${NC}"
  echo -e "  ${CYAN}tailscale login --login-server https://headscale.${DOMAIN}${NC}"
  echo ""

  echo -e "${YELLOW}${BOLD}First-boot checklist:${NC}"
  echo ""
  echo -e "  ${GREEN}✓ Automatically configured during install:${NC}"
  echo -e "    • Authentik admin username"
  echo -e "    • Nextcloud OIDC"
  echo -e "    • Audiobookshelf OIDC"
  echo -e "    • Uptime Kuma admin account"
  echo -e "    • qBittorrent credentials (username: ${ADMIN_USER})"
  echo -e "    • Headscale user + pre-auth key (printed above)"
  echo ""
  # STORAGEBOX_HOST is only set when the user opted in; USE_STORAGE_BOX flips to false on mount failure
  if [[ -n "${STORAGEBOX_HOST:-}" && "${USE_STORAGE_BOX}" == "false" ]]; then
    echo -e "  ${YELLOW}${BOLD}⚠  Storage Box — mount failed during install (using local storage)${NC}"
    echo -e "  [ ] Verify Samba is enabled in Hetzner Robot for ${STORAGEBOX_HOST}"
    echo -e "      Then remount and restart: ${CYAN}mount ${STORAGEBOX_MOUNT} && ./scripts/start.sh${NC}"
    echo ""
  fi
  echo -e "  ${BOLD}Still requires manual setup:${NC}"
  echo -e "  [ ] Jellyfin   https://jellyfin.${DOMAIN}"
  echo -e "      Complete setup wizard; add media libraries"
  echo -e "  [ ] Jellyseerr https://requests.${DOMAIN}  (do after Jellyfin)"
  echo -e "      Connect to Jellyfin in the setup wizard"
  echo ""
  echo -e "  ${BOLD}Connect Tailscale/Headscale devices:${NC}"
  echo -e "      ${CYAN}tailscale login --login-server https://headscale.${DOMAIN} --authkey <key above>${NC}"
  echo -e "      Generate a new key at any time: ${CYAN}./scripts/configure-headscale.sh${NC}"
  echo ""
  echo -e "  ${BOLD}Optional:${NC}"
  echo -e "  [ ] Jellyfin OIDC plugin — Dashboard → Plugins → Catalog"
  echo -e "  [ ] Vaultwarden admin panel — https://vault.${DOMAIN}/admin"
  echo -e "      Password: AUTHENTIK_BOOTSTRAP_TOKEN from .env"
  echo ""

  echo -e "  Start:  ${CYAN}./scripts/start.sh${NC}  (checks Storage Box, then brings stack up)"
  echo -e "  Logs:   ${CYAN}docker compose logs -f [service]${NC}"
  echo -e "  Stop:   ${CYAN}docker compose down${NC}"
  echo -e "  Update: ${CYAN}docker compose pull && docker compose up -d${NC}"
  echo ""
}

prompt_storage_box() {
  echo ""
  step "Storage configuration"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

  read -rp "$(echo -e "${YELLOW}Use a Hetzner Storage Box for media & downloads? [y/N]${NC}: ")" _use_sb
  if [[ "${_use_sb,,}" == "y" ]]; then
    USE_STORAGE_BOX=true

    while [[ -z "${STORAGEBOX_HOST:-}" ]]; do
      read -rp "$(echo -e "${YELLOW}Storage Box hostname${NC} (e.g. u123456.your-storagebox.de): ")" STORAGEBOX_HOST
    done

    while [[ -z "${STORAGEBOX_USER:-}" ]]; do
      read -rp "$(echo -e "${YELLOW}Storage Box username${NC} (e.g. u123456): ")" STORAGEBOX_USER
    done

    while [[ -z "${STORAGEBOX_PASS:-}" ]]; do
      read -rsp "$(echo -e "${YELLOW}Storage Box password${NC}: ")" STORAGEBOX_PASS; echo
    done

    # For the main Hetzner account the SMB share name is 'backup'; sub-users use their own name
    read -rp "$(echo -e "${YELLOW}SMB share name${NC} [backup]: ")" _share
    STORAGEBOX_SHARE="${_share:-backup}"

    read -rp "$(echo -e "${YELLOW}Mount point${NC} [/mnt/storagebox]: ")" _mount
    STORAGEBOX_MOUNT="${_mount:-/mnt/storagebox}"

    # Local dirs are the safe fallback; storage box paths become the active dirs
    MEDIA_DIR_LOCAL="./data/media"
    DOWNLOADS_DIR_LOCAL="./data/downloads"
    MEDIA_DIR="${STORAGEBOX_MOUNT}/media"
    DOWNLOADS_DIR="${STORAGEBOX_MOUNT}/downloads"

    success "Storage Box configured: //${STORAGEBOX_HOST}/${STORAGEBOX_SHARE} → ${STORAGEBOX_MOUNT}"
  else
    USE_STORAGE_BOX=false
    MEDIA_DIR="${MEDIA_DIR:-./data/media}"
    DOWNLOADS_DIR="./data/downloads"
    MEDIA_DIR_LOCAL="${MEDIA_DIR}"
    DOWNLOADS_DIR_LOCAL="${DOWNLOADS_DIR}"
    info "Using local storage for media"
  fi
}

setup_storage_box_mount() {
  [[ "${USE_STORAGE_BOX}" != "true" ]] && return 0

  step "Setting up Hetzner Storage Box mount"

  if ! command -v mount.cifs &>/dev/null; then
    info "Installing cifs-utils..."
    apt-get update -qq && apt-get install -y -qq cifs-utils \
      || die "Failed to install cifs-utils — install it manually and re-run"
  fi

  # Ensure CIFS kernel module is loaded (nls_utf8 not available on all kernels)
  modprobe cifs 2>/dev/null || true

  local creds_file="/root/.storagebox-credentials"
  printf 'username=%s\npassword=%s\n' "${STORAGEBOX_USER}" "${STORAGEBOX_PASS}" > "$creds_file"
  chmod 600 "$creds_file"

  mkdir -p "${STORAGEBOX_MOUNT}"

  local share="//${STORAGEBOX_HOST}/${STORAGEBOX_SHARE:-backup}"
  info "Mounting ${share} → ${STORAGEBOX_MOUNT}..."
  # iocharset=utf8 omitted — nls_utf8 module absent on many cloud kernels; SMB3 is unicode-native
  if ! mount -t cifs "$share" "${STORAGEBOX_MOUNT}" \
    -o "credentials=${creds_file},uid=${PUID},gid=${PGID},vers=3.0"; then
    warn "Mount failed. Common causes:"
    warn "  • Samba access not enabled for this Storage Box in Hetzner Robot"
    warn "  • Wrong credentials or hostname"
    warn "  • TCP 445 blocked by firewall"
    warn "Continuing install with local storage. Re-run after fixing Storage Box access."
    USE_STORAGE_BOX=false
    MEDIA_DIR="${MEDIA_DIR_LOCAL}"
    DOWNLOADS_DIR="${DOWNLOADS_DIR_LOCAL}"
    return 0
  fi

  mkdir -p \
    "${STORAGEBOX_MOUNT}/media/movies" \
    "${STORAGEBOX_MOUNT}/media/tv" \
    "${STORAGEBOX_MOUNT}/media/music" \
    "${STORAGEBOX_MOUNT}/media/books" \
    "${STORAGEBOX_MOUNT}/media/audiobooks" \
    "${STORAGEBOX_MOUNT}/media/podcasts" \
    "${STORAGEBOX_MOUNT}/downloads/complete" \
    "${STORAGEBOX_MOUNT}/downloads/incomplete"

  # _netdev  = wait for network before mounting on boot
  # nofail   = don't halt boot if the Storage Box is unreachable
  local fstab_entry="${share} ${STORAGEBOX_MOUNT} cifs credentials=${creds_file},uid=${PUID},gid=${PGID},vers=3.0,_netdev,nofail 0 0"
  # STORAGEBOX_SHARE is saved to .env above — start.sh mounts via fstab so it picks up the right share
  if ! grep -qF "${STORAGEBOX_MOUNT}" /etc/fstab; then
    echo "$fstab_entry" >> /etc/fstab
    success "fstab entry added (auto-mounts on reboot with nofail)"
  else
    info "fstab entry already exists — skipping"
  fi

  success "Storage Box mounted at ${STORAGEBOX_MOUNT}"
}

# Checks mount health and exports MEDIA_DIR / DOWNLOADS_DIR for this shell
# session so docker compose picks up the right paths. Falls back to local
# storage with a clear warning if the Storage Box is unreachable.
verify_mount_health() {
  [[ "${USE_STORAGE_BOX:-false}" != "true" ]] && return 0

  local mount_ok=false

  if mountpoint -q "${STORAGEBOX_MOUNT}" 2>/dev/null; then
    if timeout 5 ls "${STORAGEBOX_MOUNT}/" &>/dev/null 2>&1; then
      mount_ok=true
    else
      warn "Storage Box mount is stale — attempting remount..."
      umount -l "${STORAGEBOX_MOUNT}" 2>/dev/null || true
    fi
  fi

  if [[ "$mount_ok" == "false" ]]; then
    info "Storage Box not mounted — attempting to mount via fstab..."
    if mount "${STORAGEBOX_MOUNT}" 2>/dev/null; then
      sleep 2
      if timeout 5 ls "${STORAGEBOX_MOUNT}/" &>/dev/null 2>&1; then
        mount_ok=true
        success "Storage Box remounted successfully"
      fi
    fi
  fi

  if [[ "$mount_ok" == "true" ]]; then
    export MEDIA_DIR="${STORAGEBOX_MOUNT}/media"
    export DOWNLOADS_DIR="${STORAGEBOX_MOUNT}/downloads"
    success "Storage Box healthy — using ${STORAGEBOX_MOUNT} for media"
  else
    export MEDIA_DIR="${MEDIA_DIR_LOCAL}"
    export DOWNLOADS_DIR="${DOWNLOADS_DIR_LOCAL}"
    echo ""
    echo -e "${YELLOW}${BOLD}  ⚠  WARNING: Hetzner Storage Box is UNAVAILABLE${NC}"
    echo -e "${YELLOW}     Falling back to LOCAL storage for media and downloads.${NC}"
    echo -e "${YELLOW}     Any media on the Storage Box will NOT be visible until${NC}"
    echo -e "${YELLOW}     the Storage Box is remounted and the stack is restarted.${NC}"
    echo ""
    echo -e "     Remount:  ${CYAN}mount ${STORAGEBOX_MOUNT}${NC}"
    echo -e "     Restart:  ${CYAN}./scripts/start.sh${NC}"
    echo ""
  fi
}

generate_start_script() {
  step "Generating scripts/start.sh"

  cat > scripts/start.sh << 'STARTSCRIPT'
#!/usr/bin/env bash
# Generated by install.sh — use this script to start the stack on subsequent boots.
# It re-checks the Hetzner Storage Box mount before bringing containers up,
# and falls back to local storage with a warning if the box is unreachable.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR/.."

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
info()    { echo -e "${CYAN}[INFO]${NC}  $*"; }
success() { echo -e "${GREEN}[OK]${NC}    $*"; }

# shellcheck source=/dev/null
set -a; source .env; set +a

if [[ "${USE_STORAGE_BOX:-false}" == "true" ]]; then
  mount_ok=false

  if mountpoint -q "${STORAGEBOX_MOUNT}" 2>/dev/null; then
    if timeout 5 ls "${STORAGEBOX_MOUNT}/" &>/dev/null 2>&1; then
      mount_ok=true
    else
      warn "Storage Box mount is stale — attempting remount..."
      umount -l "${STORAGEBOX_MOUNT}" 2>/dev/null || true
    fi
  fi

  if [[ "$mount_ok" == "false" ]]; then
    info "Storage Box not mounted — attempting to mount via fstab..."
    if mount "${STORAGEBOX_MOUNT}" 2>/dev/null; then
      sleep 2
      if timeout 5 ls "${STORAGEBOX_MOUNT}/" &>/dev/null 2>&1; then
        mount_ok=true
        success "Storage Box remounted successfully"
      fi
    fi
  fi

  if [[ "$mount_ok" == "true" ]]; then
    export MEDIA_DIR="${STORAGEBOX_MOUNT}/media"
    export DOWNLOADS_DIR="${STORAGEBOX_MOUNT}/downloads"
    success "Storage Box healthy — using ${STORAGEBOX_MOUNT} for media"
  else
    export MEDIA_DIR="${MEDIA_DIR_LOCAL}"
    export DOWNLOADS_DIR="${DOWNLOADS_DIR_LOCAL}"
    echo ""
    echo -e "${YELLOW}${BOLD}  ⚠  WARNING: Hetzner Storage Box is UNAVAILABLE${NC}"
    echo -e "${YELLOW}     Falling back to LOCAL storage for media and downloads.${NC}"
    echo -e "${YELLOW}     Any media on the Storage Box will NOT be visible until${NC}"
    echo -e "${YELLOW}     the Storage Box is remounted and the stack is restarted.${NC}"
    echo ""
    echo -e "     Remount:  ${CYAN}mount ${STORAGEBOX_MOUNT}${NC}"
    echo -e "     Restart:  ${CYAN}$(realpath "$0")${NC}"
    echo ""
  fi
fi

exec docker compose up -d "$@"
STARTSCRIPT

  chmod +x scripts/start.sh
  success "scripts/start.sh generated"
}

main() {
  print_banner
  check_requirements
  prompt_config
  prompt_storage_box
  generate_secrets
  write_env
  create_directories
  setup_storage_box_mount
  process_templates
  verify_mount_health
  start_stack
  configure_services
  generate_start_script
  print_summary
}

main "$@"
