#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# Ultimate Self-Hosted Stack Installer
# ============================================================

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

print_banner() {
  echo -e "${BLUE}${BOLD}"
  cat << 'BANNER'
╔══════════════════════════════════════════════════════════════╗
║           Ultimate Self-Hosted Stack Installer               ║
║                                                              ║
║  Traefik · Authentik · Homarr · Jellyfin · Nextcloud        ║
║  Navidrome · Sonarr/Radarr/Lidarr · Headscale · VPN        ║
║  Vaultwarden · Grafana · Uptime Kuma · and more...          ║
╚══════════════════════════════════════════════════════════════╝
BANNER
  echo -e "${NC}"
}

info()    { echo -e "${CYAN}[INFO]${NC}  $*"; }
success() { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; }
step()    { echo -e "\n${BOLD}${BLUE}▶ $*${NC}"; }

die() { error "$*"; exit 1; }

check_requirements() {
  step "Checking requirements"
  local missing=()

  command -v docker   &>/dev/null || missing+=("docker")
  docker compose version &>/dev/null 2>&1 || missing+=("docker-compose-plugin (v2)")
  command -v curl     &>/dev/null || missing+=("curl")
  command -v openssl  &>/dev/null || missing+=("openssl")
  command -v python3  &>/dev/null || warn "python3 not found — WireGuard password hash will be skipped"

  if [[ ${#missing[@]} -gt 0 ]]; then
    die "Missing required tools: ${missing[*]}"
  fi

  # Verify Docker daemon is running
  docker info &>/dev/null || die "Docker daemon is not running"

  success "All requirements met"
}

gen_secret()   { openssl rand -hex 32; }
gen_short_id() { openssl rand -hex 8; }

prompt_config() {
  step "Configuration"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

  while [[ -z "${ADMIN_USER:-}" ]]; do
    read -rp "$(echo -e "${YELLOW}Admin username${NC}: ")" ADMIN_USER
  done

  while true; do
    read -rsp "$(echo -e "${YELLOW}Admin password${NC}: ")" ADMIN_PASSWORD; echo
    read -rsp "$(echo -e "${YELLOW}Confirm password${NC}: ")" _confirm; echo
    [[ "$ADMIN_PASSWORD" == "$_confirm" ]] && [[ -n "$ADMIN_PASSWORD" ]] && break
    warn "Passwords do not match or are empty — try again"
  done

  while [[ -z "${DOMAIN:-}" ]]; do
    read -rp "$(echo -e "${YELLOW}Fully qualified domain (e.g. example.com)${NC}: ")" DOMAIN
    # Strip protocol/trailing slash
    DOMAIN="${DOMAIN#https://}"; DOMAIN="${DOMAIN#http://}"; DOMAIN="${DOMAIN%/}"
  done

  read -rp "$(echo -e "${YELLOW}Admin email${NC} [admin@${DOMAIN}]: ")" ADMIN_EMAIL
  ADMIN_EMAIL="${ADMIN_EMAIL:-admin@${DOMAIN}}"

  read -rp "$(echo -e "${YELLOW}Timezone${NC} [America/New_York]: ")" TZ
  TZ="${TZ:-America/New_York}"

  read -rp "$(echo -e "${YELLOW}Media directory${NC} [./data/media]: ")" MEDIA_DIR
  MEDIA_DIR="${MEDIA_DIR:-./data/media}"

  read -rp "$(echo -e "${YELLOW}PUID${NC} [1000]: ")" PUID
  PUID="${PUID:-1000}"

  read -rp "$(echo -e "${YELLOW}PGID${NC} [1000]: ")" PGID
  PGID="${PGID:-1000}"

  echo ""
  success "Configuration captured"
}

generate_secrets() {
  step "Generating secrets"

  POSTGRES_PASSWORD=$(gen_secret)
  REDIS_PASSWORD=$(gen_secret)
  AUTHENTIK_SECRET_KEY=$(gen_secret)
  AUTHENTIK_BOOTSTRAP_TOKEN=$(gen_secret)
  NEXTCLOUD_DB_PASSWORD=$(gen_secret)

  HOMARR_OIDC_CLIENT_ID="homarr-$(gen_short_id)"
  HOMARR_OIDC_CLIENT_SECRET=$(gen_secret)

  AUDIOBOOKSHELF_OIDC_CLIENT_ID="abs-$(gen_short_id)"
  AUDIOBOOKSHELF_OIDC_CLIENT_SECRET=$(gen_secret)

  NEXTCLOUD_OIDC_CLIENT_ID="nextcloud-$(gen_short_id)"
  NEXTCLOUD_OIDC_CLIENT_SECRET=$(gen_secret)

  GRAFANA_OIDC_CLIENT_ID="grafana-$(gen_short_id)"
  GRAFANA_OIDC_CLIENT_SECRET=$(gen_secret)

  VAULTWARDEN_OIDC_CLIENT_ID="vaultwarden-$(gen_short_id)"
  VAULTWARDEN_OIDC_CLIENT_SECRET=$(gen_secret)

  # WireGuard bcrypt password hash
  if command -v python3 &>/dev/null && python3 -c "import bcrypt" &>/dev/null 2>&1; then
    WG_PASSWORD_HASH=$(python3 -c "import bcrypt; print(bcrypt.hashpw('${ADMIN_PASSWORD}'.encode(), bcrypt.gensalt(12)).decode())")
  elif command -v python3 &>/dev/null; then
    python3 -m pip install bcrypt -q 2>/dev/null || true
    WG_PASSWORD_HASH=$(python3 -c "import bcrypt; print(bcrypt.hashpw('${ADMIN_PASSWORD}'.encode(), bcrypt.gensalt(12)).decode())" 2>/dev/null || echo "")
  fi
  WG_PASSWORD_HASH="${WG_PASSWORD_HASH:-}"

  success "Secrets generated"
}

write_env() {
  step "Writing .env"

  cat > .env << EOF
# ================================================================
# Generated by install.sh — DO NOT COMMIT THIS FILE
# ================================================================

# ── Core ─────────────────────────────────────────────────────────
DOMAIN=${DOMAIN}
ADMIN_USER=${ADMIN_USER}
ADMIN_PASSWORD=${ADMIN_PASSWORD}
ADMIN_EMAIL=${ADMIN_EMAIL}
TZ=${TZ}
PUID=${PUID}
PGID=${PGID}
MEDIA_DIR=${MEDIA_DIR}
DOWNLOADS_DIR=./data/downloads

# ── Databases ────────────────────────────────────────────────────
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
REDIS_PASSWORD=${REDIS_PASSWORD}
NEXTCLOUD_DB_PASSWORD=${NEXTCLOUD_DB_PASSWORD}

# ── Authentik ────────────────────────────────────────────────────
AUTHENTIK_SECRET_KEY=${AUTHENTIK_SECRET_KEY}
AUTHENTIK_BOOTSTRAP_TOKEN=${AUTHENTIK_BOOTSTRAP_TOKEN}

# ── OIDC Clients ─────────────────────────────────────────────────
HOMARR_OIDC_CLIENT_ID=${HOMARR_OIDC_CLIENT_ID}
HOMARR_OIDC_CLIENT_SECRET=${HOMARR_OIDC_CLIENT_SECRET}

AUDIOBOOKSHELF_OIDC_CLIENT_ID=${AUDIOBOOKSHELF_OIDC_CLIENT_ID}
AUDIOBOOKSHELF_OIDC_CLIENT_SECRET=${AUDIOBOOKSHELF_OIDC_CLIENT_SECRET}

NEXTCLOUD_OIDC_CLIENT_ID=${NEXTCLOUD_OIDC_CLIENT_ID}
NEXTCLOUD_OIDC_CLIENT_SECRET=${NEXTCLOUD_OIDC_CLIENT_SECRET}

GRAFANA_OIDC_CLIENT_ID=${GRAFANA_OIDC_CLIENT_ID}
GRAFANA_OIDC_CLIENT_SECRET=${GRAFANA_OIDC_CLIENT_SECRET}

VAULTWARDEN_OIDC_CLIENT_ID=${VAULTWARDEN_OIDC_CLIENT_ID}
VAULTWARDEN_OIDC_CLIENT_SECRET=${VAULTWARDEN_OIDC_CLIENT_SECRET}

# ── WireGuard Easy ───────────────────────────────────────────────
WG_HOST=${DOMAIN}
WG_DEFAULT_DNS=1.1.1.1,1.0.0.1
WG_MTU=1420
WG_PASSWORD_HASH=${WG_PASSWORD_HASH}
EOF

  chmod 600 .env
  success ".env written (permissions 600)"
}

create_directories() {
  step "Creating directory structure"

  local dirs=(
    data/traefik
    data/authentik/media
    data/authentik/custom-templates
    data/homarr/configs
    data/homarr/data
    data/homarr/icons
    data/jellyfin/config
    data/jellyfin/cache
    data/jellyseerr
    data/audiobookshelf/config
    data/audiobookshelf/metadata
    data/booklore
    data/navidrome
    data/sonarr
    data/radarr
    data/lidarr
    data/prowlarr
    data/qbittorrent
    data/nextcloud
    data/headscale
    data/wireguard
    data/uptime-kuma
    data/prometheus
    data/grafana
    data/vaultwarden
    data/media/movies
    data/media/tv
    data/media/music
    data/media/books
    data/media/audiobooks
    data/media/podcasts
    data/downloads/complete
    data/downloads/incomplete
  )

  for d in "${dirs[@]}"; do
    mkdir -p "$d"
  done

  # acme.json must be 600 or Traefik refuses to use it
  touch data/traefik/acme.json
  chmod 600 data/traefik/acme.json

  success "Directories created"
}

process_templates() {
  step "Processing configuration templates"

  find config -name "*.template" | while read -r tmpl; do
    local output="${tmpl%.template}"
    sed \
      -e "s|{{DOMAIN}}|${DOMAIN}|g" \
      -e "s|{{ADMIN_USER}}|${ADMIN_USER}|g" \
      -e "s|{{ADMIN_EMAIL}}|${ADMIN_EMAIL}|g" \
      -e "s|{{POSTGRES_PASSWORD}}|${POSTGRES_PASSWORD}|g" \
      -e "s|{{REDIS_PASSWORD}}|${REDIS_PASSWORD}|g" \
      -e "s|{{AUTHENTIK_SECRET_KEY}}|${AUTHENTIK_SECRET_KEY}|g" \
      -e "s|{{AUTHENTIK_BOOTSTRAP_TOKEN}}|${AUTHENTIK_BOOTSTRAP_TOKEN}|g" \
      -e "s|{{HOMARR_OIDC_CLIENT_ID}}|${HOMARR_OIDC_CLIENT_ID}|g" \
      -e "s|{{HOMARR_OIDC_CLIENT_SECRET}}|${HOMARR_OIDC_CLIENT_SECRET}|g" \
      -e "s|{{AUDIOBOOKSHELF_OIDC_CLIENT_ID}}|${AUDIOBOOKSHELF_OIDC_CLIENT_ID}|g" \
      -e "s|{{AUDIOBOOKSHELF_OIDC_CLIENT_SECRET}}|${AUDIOBOOKSHELF_OIDC_CLIENT_SECRET}|g" \
      -e "s|{{NEXTCLOUD_OIDC_CLIENT_ID}}|${NEXTCLOUD_OIDC_CLIENT_ID}|g" \
      -e "s|{{NEXTCLOUD_OIDC_CLIENT_SECRET}}|${NEXTCLOUD_OIDC_CLIENT_SECRET}|g" \
      -e "s|{{GRAFANA_OIDC_CLIENT_ID}}|${GRAFANA_OIDC_CLIENT_ID}|g" \
      -e "s|{{GRAFANA_OIDC_CLIENT_SECRET}}|${GRAFANA_OIDC_CLIENT_SECRET}|g" \
      -e "s|{{VAULTWARDEN_OIDC_CLIENT_ID}}|${VAULTWARDEN_OIDC_CLIENT_ID}|g" \
      -e "s|{{VAULTWARDEN_OIDC_CLIENT_SECRET}}|${VAULTWARDEN_OIDC_CLIENT_SECRET}|g" \
      -e "s|{{TZ}}|${TZ}|g" \
      "$tmpl" > "$output"
    info "  $(basename "$tmpl") → $(basename "$output")"
  done

  success "Templates processed"
}

start_stack() {
  step "Starting the stack"

  info "[1/5] Pulling images (this may take several minutes)..."
  docker compose pull --quiet

  info "[2/5] Starting databases..."
  docker compose up -d postgres redis

  info "      Waiting for PostgreSQL..."
  local retries=0
  until docker compose exec -T postgres pg_isready -U postgres &>/dev/null; do
    retries=$((retries+1))
    [[ $retries -gt 30 ]] && die "PostgreSQL did not become healthy in time"
    sleep 2
  done
  success "      PostgreSQL ready"

  info "      Waiting for Redis..."
  retries=0
  until docker compose exec -T redis redis-cli -a "${REDIS_PASSWORD}" ping &>/dev/null; do
    retries=$((retries+1))
    [[ $retries -gt 20 ]] && die "Redis did not become healthy in time"
    sleep 2
  done
  success "      Redis ready"

  info "[3/5] Starting Authentik (first run takes ~90s)..."
  docker compose up -d authentik-server authentik-worker

  info "      Waiting for Authentik API..."
  retries=0
  until curl -sf --max-time 5 "http://localhost:9000/api/v3/root/config/" &>/dev/null 2>&1; do
    retries=$((retries+1))
    [[ $retries -gt 60 ]] && {
      warn "Authentik is slow to start. Check: docker compose logs authentik-server"
      warn "You can run 'docker compose up -d' manually once Authentik is ready."
      return 0
    }
    sleep 3
  done
  success "      Authentik ready"

  info "[4/5] Starting remaining services..."
  docker compose up -d

  info "[5/5] Waiting for all services to stabilize..."
  sleep 10

  success "Stack started"
}

print_summary() {
  echo ""
  echo -e "${GREEN}${BOLD}"
  cat << 'DONE'
╔══════════════════════════════════════════════════════════════╗
║                    Setup Complete!  🎉                       ║
╚══════════════════════════════════════════════════════════════╝
DONE
  echo -e "${NC}"

  echo -e "${BOLD}Service URLs:${NC}"
  printf "  %-18s → ${BLUE}https://home.%s${NC}\n"       "Dashboard (Homarr)"    "${DOMAIN}"
  printf "  %-18s → ${BLUE}https://auth.%s${NC}\n"       "Auth (Authentik)"      "${DOMAIN}"
  printf "  %-18s → ${BLUE}https://jellyfin.%s${NC}\n"   "Jellyfin"              "${DOMAIN}"
  printf "  %-18s → ${BLUE}https://requests.%s${NC}\n"   "Jellyseerr"            "${DOMAIN}"
  printf "  %-18s → ${BLUE}https://audiobooks.%s${NC}\n" "Audiobookshelf"        "${DOMAIN}"
  printf "  %-18s → ${BLUE}https://books.%s${NC}\n"      "Booklore"              "${DOMAIN}"
  printf "  %-18s → ${BLUE}https://music.%s${NC}\n"      "Navidrome"             "${DOMAIN}"
  printf "  %-18s → ${BLUE}https://sonarr.%s${NC}\n"     "Sonarr"                "${DOMAIN}"
  printf "  %-18s → ${BLUE}https://radarr.%s${NC}\n"     "Radarr"                "${DOMAIN}"
  printf "  %-18s → ${BLUE}https://lidarr.%s${NC}\n"     "Lidarr"                "${DOMAIN}"
  printf "  %-18s → ${BLUE}https://prowlarr.%s${NC}\n"   "Prowlarr"              "${DOMAIN}"
  printf "  %-18s → ${BLUE}https://qbit.%s${NC}\n"       "qBittorrent"           "${DOMAIN}"
  printf "  %-18s → ${BLUE}https://cloud.%s${NC}\n"      "Nextcloud"             "${DOMAIN}"
  printf "  %-18s → ${BLUE}https://headscale.%s${NC}\n"  "Headscale"             "${DOMAIN}"
  printf "  %-18s → ${BLUE}https://vpn.%s${NC}\n"        "WireGuard Easy"        "${DOMAIN}"
  printf "  %-18s → ${BLUE}https://uptime.%s${NC}\n"     "Uptime Kuma"           "${DOMAIN}"
  printf "  %-18s → ${BLUE}https://grafana.%s${NC}\n"    "Grafana"               "${DOMAIN}"
  printf "  %-18s → ${BLUE}https://vault.%s${NC}\n"      "Vaultwarden"           "${DOMAIN}"
  printf "  %-18s → ${BLUE}https://traefik.%s${NC}\n"    "Traefik Dashboard"     "${DOMAIN}"

  echo ""
  echo -e "${BOLD}Admin credentials:${NC}"
  echo -e "  Username: ${GREEN}${ADMIN_USER}${NC}"
  echo -e "  Password: ${GREEN}(the password you entered)${NC}"
  echo ""
  echo -e "${BOLD}Headscale client connection:${NC}"
  echo -e "  ${CYAN}tailscale login --login-server https://headscale.${DOMAIN}${NC}"
  echo ""
  echo -e "${YELLOW}${BOLD}Important next steps:${NC}"
  echo -e "  1. Point DNS A/CNAME records (or wildcard *.${DOMAIN}) to this server's IP"
  echo -e "  2. Port 80, 443, and 51820/UDP must be open in your firewall"
  echo -e "  3. Authentik at https://auth.${DOMAIN} — Blueprints auto-configure OIDC"
  echo -e "  4. For Jellyfin OIDC: install SSO plugin from the plugin catalog"
  echo -e "  5. For Nextcloud OIDC: run scripts/configure-nextcloud-oidc.sh after boot"
  echo -e "  6. ARR services: configure with 'Authentication: External' in their settings"
  echo ""
  echo -e "  Logs: ${CYAN}docker compose logs -f [service]${NC}"
  echo -e "  Stop: ${CYAN}docker compose down${NC}"
  echo -e "  Update: ${CYAN}docker compose pull && docker compose up -d${NC}"
  echo ""
}

main() {
  print_banner
  check_requirements
  prompt_config
  generate_secrets
  write_env
  create_directories
  process_templates
  start_stack
  print_summary
}

main "$@"
